default: &defaults
  push_api_key:
  name: ""

development:
  <<: *defaults
  active: true
  ignore_exceptions:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError

production:
  <<: *defaults
  active: true
  ignore_exceptions:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError
